# Generated by Django 3.0.3 on 2026-06-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_dayoff_weeklyschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('method', models.IntegerField(choices=[(1, 'Dinheiro'), (2, 'Cartão de Crédito'), (3, 'Cartão de Débito')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Pago'), (3, 'Estornado')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='website.Appointment')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='website.Appointment')),
            ],
            options={
                'verbose_name': 'Detalhes da Consulta',
                'verbose_name_plural': 'Detalhes das Consultas',
            },
        ),
    ]
