# Generated by Django 3.0.3 on 2026-06-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
